# Generated by Django 2.2 on 2019-11-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pub_dte',
            new_name='pub_date',
        ),
    ]
